//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkartDataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public System.Guid ShoopingCartId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public int ProductId { get; set; }
        public Nullable<bool> AnonymousUser { get; set; }
        public Nullable<int> Quatity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
