//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkartDataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueTypeGroup
    {
        public ValueTypeGroup()
        {
            this.ValueTypes = new HashSet<ValueType>();
        }
    
        public int ValueTypeGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<ValueType> ValueTypes { get; set; }
    }
}
